[package]
name = "tenor-analyze"
version.workspace = true
edition.workspace = true
description = "Tenor static analyzer"

[dependencies]
tenor-core = { path = "../core" }
serde = { workspace = true }
serde_json = { workspace = true }
