[package]
name = "tenor-codegen"
version.workspace = true
edition.workspace = true
description = "Tenor code generator"

[dependencies]
tenor-interchange = { path = "../interchange" }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
tempfile = "3"
